db.restaurant.find().pretty()
db.restaurant.find({},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurant.find({},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurant.find({},{_id:0, restaurant_id:1, name:1, borough:1, address:{zipcode:1}})
db.restaurant.find({borough:"Bronx"}).pretty()
db.restaurant.find({borough:"Bronx"}).limit(5).pretty()
db.restaurant.find({borough:"Bronx"}).skip(5).limit(5).pretty()
db.restaurant.find({"grades.score":{$gt:90}}).pretty()
db.restaurant.find({grades :{$elemMatch:{score:{$gt:80, $lt:100}}}}).pretty()
db.restaurant.find({"address.coord.0":{$gt: -95.754168}}).pretty()
db.restaurant.find({"address.coord.0":{$gt: -65.754168}, "cuisine":{$ne:"American "},"grades.score":{$gt:70} }).pretty()
db.restaurant.find({"address.coord.1":{$gt: -65.754168}, "cuisine":{$ne:"American "},"grades.score":{$gt:70} }).pretty()
db.restaurant.find({"borough":{$ne:"Brooklyn"}, "cuisine":{$ne:"American "},"grades.grade":"A"}).sort({"cuisine":-1}).pretty()
db.restaurant.find({name:/^Wil/},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({name:/ces$/},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({name:/Reg/},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({borough:"Bronx", $or: [{"cuisine":"American "}, {"cuisine":"Chinese"}]}).pretty()
db.restaurant.find({$or: [{"borough":"Staten Island"}, {"borough":"Queens"},{"borough":"Bronx"}, {"borough":"Brooklyn"}]},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({$and: [{"borough":{$ne:"Staten Island"}}, {"borough":{$ne:"Queens"}}, {"borough":{$ne:"Bronx"}}, {"borough":{$ne:"Brooklyn"}}]},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({"grades.score":{$lt:10}},{_id:0, restaurant_id:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({$and: [{"cuisine":"Seafood"}, {"name": {$not: /^Wil/}}]},{_id:0, restaurant_id:1, name:1, borough:1, cuisine:1}).pretty()
db.restaurant.find({"grades" : {$elemMatch: {"grade" : "A", "score" : 11, "date":ISODate("2014-08-11T00:00:00Z")}}},{_id:0, restaurant_id:1, name:1, grades:1}).pretty()
db.restaurant.find({"grades.1.score":9, "grades.1.grade":"A", "grades.1.date":ISODate("2014-08-11T00:00:00Z")},{_id:0, restaurant_id:1, name:1, grades:1}).pretty()
db.restaurant.find({"address.coord.1":{$gt: 42, $lt:52}},{_id:0, restaurant_id:1, address:1}).pretty()
db.restaurant.find().sort({"name":1}).pretty()
db.restaurant.find().sort({"name":-1}).pretty()
db.restaurant.find().sort({"cuisine":1, "borough":-1}).pretty()
db.restaurant.find({"address.street": {$exists:true}}).pretty()
db.restaurant.find({"address.coord": {$type:1}}).pretty()
db.restaurant.find({"grades" : {$elemMatch: {score: { $mod: [5,0] }}}},{_id:0, restaurant_id:1, name:1, grade:1})
db.restaurant.find({name:/mon/},{_id:0, restaurant_id:1, name:1, borough:1, "address.coord":1})
db.restaurant.find({name:/^Mad/},{_id:0, restaurant_id:1, name:1, borough:1, "address.coord":1})
